apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
spec:
  datasource: datacollector
  httpsCertsSource: self-signed
  httpsEnable: true
  instanceNamespace: ibm-common-services
